In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2083, 0.0718, 0.2802],
        [0.3267, 0.2215, 0.9612],
        [0.1980, 0.6843, 0.6263],
        [0.6396, 0.6270, 0.9325],
        [0.3066, 0.9611, 0.8704]])


Get its size



In [4]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [5]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6994, 0.7964, 0.6191],
        [0.6626, 1.0911, 1.7002],
        [0.5491, 1.4849, 0.8814],
        [0.8507, 1.5290, 1.2735],
        [0.5461, 1.1880, 1.6890]])


Addition: syntax 2



In [6]:
print(torch.add(x, y))

tensor([[0.6994, 0.7964, 0.6191],
        [0.6626, 1.0911, 1.7002],
        [0.5491, 1.4849, 0.8814],
        [0.8507, 1.5290, 1.2735],
        [0.5461, 1.1880, 1.6890]])


Addition: giving an output tensor



In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6994, 0.7964, 0.6191],
        [0.6626, 1.0911, 1.7002],
        [0.5491, 1.4849, 0.8814],
        [0.8507, 1.5290, 1.2735],
        [0.5461, 1.1880, 1.6890]])


Addition: in-place



In [8]:
# adds x to y
y.add_(x)
print(y)

tensor([[0.6994, 0.7964, 0.6191],
        [0.6626, 1.0911, 1.7002],
        [0.5491, 1.4849, 0.8814],
        [0.8507, 1.5290, 1.2735],
        [0.5461, 1.1880, 1.6890]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [9]:
print(x[:, 1])

tensor([0.0718, 0.2215, 0.6843, 0.6270, 0.9611])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [10]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [12]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y